schema = 3

[mod]
  [mod."github.com/RageCage64/go-utf8-codepoint-converter"]
    version = "v0.1.0"
    hash = "sha256-hvu/YVd2ct6XVhZpKoUYnKw9jP3H0aYdeSmGN3jx9Z0="
  [mod."github.com/RageCage64/multilinediff"]
    version = "v0.2.0"
    hash = "sha256-2+a5bHiRoJWyvrFqYTF010s2ZLQs7UrQzaeIFn9HJSk="
  [mod."github.com/bmatcuk/doublestar/v4"]
    version = "v4.2.0"
    hash = "sha256-7xnw1NxJQhpCrOiWOxIgpztSFAgsRJu2w1xlbRR3Tac="
  [mod."github.com/google/go-cmp"]
    version = "v0.5.9"
    hash = "sha256-lQc4O00R3QSMGs9LP8Sy7A9kj0cqV5rrUdpnGeipIyg="
  [mod."github.com/mitchellh/mapstructure"]
    version = "v1.5.0"
    hash = "sha256-ztVhGQXs67MF8UadVvG72G3ly0ypQW0IRDdOOkjYwoE="
  [mod."gopkg.in/yaml.v3"]
    version = "v3.0.1"
    hash = "sha256-FqL9TKYJ0XkNwJFnq9j0VvJ5ZUU1RvH/52h/f5bkYAU="
