[formatter.alejandra]
command = "alejandra"
includes = ["*.nix"]

[formatter.yamlfmt]
command = "yamlfmt"
includes = ["*.yml", "*.yaml"]

[formatter.taplo]
command = "taplo"
options = ["fmt"]
includes = ["*.toml"]
excludes = ["gomod2nix.toml"]
